### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by AlexMRuch** [RoyZhengGao/edge2vec#2]
The following link is broken: The output is the node embedding file vector.txt. Data repository for medical dataset in the link: http://ella.ils.indiana.edu/~gao27/data_repo/edge2vec vector.zip

**Comment by RoyZhengGao** [comment]
thanks for letting me know. I forget to use %20 to replace space.

**Comment by AlexMRuch** [comment]
No problem! Looking forward to checking your code out and applying it! Thanks!

**Comment by RoyZhengGao** [comment]
Thanks for pointing that out. The result is a re-computed version which may be slightly different with the result reported in the paper.
